name: "test"
on:
  push:
    branches-ignore: [develop, release-*]
    tags-ignore: ["*"]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Format and run test
        run: |-
          go fmt
          go test
